### ISSUE TITLE
Uso de system

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_2122-the_dream_team#9]
La función `system` permite ejecutar comandos del sistema operativo. Por tanto, su inclusión dentro del código implica que éste no es portable (es decir, únicamente se puede compilar y ejecutar en un sistema operativo). Debéis eliminar su uso y sustituirlo por otras opciones (mirad el punto 5 de [este documento](https://github.com/oscarperpinan/informatica_etsidi/raw/master/ejercicios/misc.pdf)).

https://github.com/aigora/twE105_2122-the_dream_team/blob/4b0b8e389971fe700ba422798d07e96118e718e3/Men%C3%BA%20Hotel%20Encantado%20completado.c#L125

**Comment by dRonda** [comment]
Buenas Oscar, he estado mirando, que te parece si utilizo esto:
fflush(stdin); 
getchar();
y así el usuario puede continuar dándole a intro

**Comment by oscarperpinan** [comment]
¿Qué diferencia hay con `scanf(" %c", &x)`?

**Comment by dRonda** [comment]
Buenas Oscar, te parece correcto que utilice lo que te he comentado en el anterior mensaje?
Y ese mensaje de respuesta del scanf no se si va para mi

**Comment by oscarperpinan** [comment]
> Y ese mensaje de respuesta del scanf no se si va para mi

Sí, claro.

**Comment by dRonda** [comment]
Perdona Oscar, estoy un poco empanado con el GitHub todavía. La verdad que el funcionamiento es el mismo, pero no se me había ocurrido y me había puesto ha buscar en internet como un loco, ahora lo cambio

**Comment by dRonda** [comment]
Por cierto, aprovecho para preguntarte, hay alguna manera de que vayan desapareciendo los printf anteriores?? (para que la pantalla vaya quedando mas limpia)

**Comment by dRonda** [comment]
> ¿Qué diferencia hay con `scanf(" %c", &x)`?

Me acabo de dar cuenta que si hay una diferencia, con mi opción si le das a intro te basta para continuar, con la opción que propones tú obligas al usuario a pulsar un caracter

**Comment by oscarperpinan** [comment]
> Me acabo de dar cuenta que si hay una diferencia, con mi opción si le das a intro te basta para continuar, con la opción que propones tú obligas al usuario a pulsar un caracter

Cierto. Mejor `getchar` entonces.
